version: '3.1'

services:

  db1:
    container_name: db1
    image: postgres:14.7-alpine
    restart: no
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "example"
    ports:
      - "5436:5432"
    volumes:
      - ./db1.sql:/docker-entrypoint-initdb.d/db.sql

  db2:
    container_name: db2
    image: postgres:14.7-alpine
    restart: no
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "example"
    ports:
      - "5437:5432"
    volumes:
      - ./db2.sql:/docker-entrypoint-initdb.d/db.sql